// Seed exercise library (PRD §6.5, §7).
//
// The PRD's cited source files (Emma_Trainerize_Workout_Knowledge.md, the PDF) are
// not present, so this starter library is derived from the PRD's own descriptions +
// the movements in workout_app_mockup.html, organized by movement pattern so every
// primary/secondary lift has >=2-3 valid same-pattern alternatives to swap to.
// Real Trainerize data can replace/augment this later (PRD §7 data-quality note).

import type { Exercise } from "../domain/types";

export const SEED_EXERCISES: Exercise[] = [
  // ── Squat pattern — quads/glutes ────────────────────────────────────────────
  {
    id: "barbell-back-squat",
    name: "Barbell back squat",
    muscleGroups: ["quads", "glutes"],
    category: "primary",
    equipment: "barbell",
    isCoreLift: true,
    defaultCues: [
      "Brace before descending",
      "Knees track over toes",
      "Drive through mid-foot",
    ],
  },
  {
    id: "goblet-squat",
    name: "Goblet squat",
    muscleGroups: ["quads", "glutes"],
    category: "secondary",
    equipment: "dumbbell",
    defaultCues: ["Elbows inside knees", "Chest tall", "Sit between the hips"],
  },
  {
    id: "bulgarian-split-squat",
    name: "Bulgarian split squat",
    muscleGroups: ["quads", "glutes"],
    category: "secondary",
    equipment: "dumbbell",
    defaultCues: [
      "Weight through front heel",
      "Vertical front shin at the bottom",
      "Square hips forward",
    ],
  },
  {
    id: "angled-leg-press",
    name: "Angled machine leg press",
    muscleGroups: ["quads", "glutes"],
    category: "secondary",
    equipment: "machine",
    defaultCues: ["Feet shoulder width", "Don't lock the knees", "Control the negative"],
  },
  {
    id: "hack-squat",
    name: "Hack squat",
    muscleGroups: ["quads", "glutes"],
    category: "secondary",
    equipment: "machine",
    defaultCues: ["Full depth", "Heels planted", "Brace the core"],
  },

  // ── Hinge pattern — posterior chain ─────────────────────────────────────────
  {
    id: "trap-bar-deadlift",
    name: "Trap bar deadlift",
    muscleGroups: ["hamstrings", "glutes", "back"],
    category: "primary",
    equipment: "trap-bar",
    isCoreLift: true,
    defaultCues: [
      "Push the ground away",
      "Brace before the pull",
      "Chest up through lockout",
    ],
  },
  {
    id: "barbell-sumo-deadlift",
    name: "Barbell sumo deadlift",
    muscleGroups: ["hamstrings", "glutes", "back"],
    category: "primary",
    equipment: "barbell",
    isCoreLift: true,
    defaultCues: ["Spread the floor", "Lats tight to the bar", "Hips and chest rise together"],
  },
  {
    id: "romanian-deadlift",
    name: "Romanian deadlift",
    muscleGroups: ["hamstrings", "glutes"],
    category: "secondary",
    equipment: "barbell",
    defaultCues: ["Soft knees", "Push hips back", "Bar stays close to the legs"],
  },
  {
    id: "db-romanian-deadlift",
    name: "Dumbbell Romanian deadlift",
    muscleGroups: ["hamstrings", "glutes"],
    category: "secondary",
    equipment: "dumbbell",
    defaultCues: ["Hinge at the hips", "Flat back", "Feel the hamstring stretch"],
  },
  {
    id: "back-extension",
    name: "Back extension",
    muscleGroups: ["hamstrings", "glutes", "lower-back"],
    category: "accessory",
    equipment: "bodyweight",
    defaultCues: ["Round then extend under control", "Squeeze glutes at the top", "No hyperextension"],
  },

  // ── Lunge — unilateral quads/glutes ─────────────────────────────────────────
  {
    id: "barbell-reverse-lunge",
    name: "Barbell reverse lunge",
    muscleGroups: ["quads", "glutes"],
    category: "secondary",
    equipment: "barbell",
    defaultCues: ["Step back under control", "Torso upright", "Push through the front heel"],
  },
  {
    id: "walking-lunge",
    name: "Dumbbell walking lunge",
    muscleGroups: ["quads", "glutes"],
    category: "secondary",
    equipment: "dumbbell",
    defaultCues: ["Long steps", "Knee tracks the toe", "Stay tall"],
  },
  {
    id: "db-step-up",
    name: "Dumbbell step-up",
    muscleGroups: ["quads", "glutes"],
    category: "secondary",
    equipment: "dumbbell",
    defaultCues: ["Full foot on the box", "Drive through the heel", "Control the way down"],
  },

  // ── Horizontal push — chest ─────────────────────────────────────────────────
  {
    id: "barbell-bench-press",
    name: "Barbell bench press",
    muscleGroups: ["chest", "triceps", "shoulders"],
    category: "primary",
    equipment: "barbell",
    isCoreLift: true,
    defaultCues: ["Shoulder blades pinned", "Bar to lower chest", "Drive feet into the floor"],
  },
  {
    id: "db-bench-press",
    name: "Dumbbell bench press",
    muscleGroups: ["chest", "triceps", "shoulders"],
    category: "secondary",
    equipment: "dumbbell",
    defaultCues: ["Wrists stacked over elbows", "Control the stretch", "Press slightly inward"],
  },
  {
    id: "machine-chest-press",
    name: "Machine chest press",
    muscleGroups: ["chest", "triceps", "shoulders"],
    category: "secondary",
    equipment: "machine",
    defaultCues: ["Handles at mid-chest", "Don't flare the elbows", "Full lockout, no slam"],
  },

  // ── Vertical push — shoulders ───────────────────────────────────────────────
  {
    id: "barbell-overhead-press",
    name: "Barbell overhead press",
    muscleGroups: ["shoulders", "triceps"],
    category: "primary",
    equipment: "barbell",
    isCoreLift: true,
    defaultCues: ["Squeeze glutes, ribs down", "Bar path past the chin", "Shrug at lockout"],
  },
  {
    id: "db-shoulder-press",
    name: "Dumbbell shoulder press",
    muscleGroups: ["shoulders", "triceps"],
    category: "secondary",
    equipment: "dumbbell",
    defaultCues: ["Neutral or slight arc", "Ribs down", "Full lockout overhead"],
  },
  {
    id: "machine-shoulder-press",
    name: "Machine shoulder press",
    muscleGroups: ["shoulders", "triceps"],
    category: "secondary",
    equipment: "machine",
    defaultCues: ["Seat height at shoulder", "Controlled negative", "Don't lean back"],
  },

  // ── Horizontal pull — back (chest-supported row is EXCLUDED for Emma) ────────
  {
    id: "seated-cable-row",
    name: "Seated cable row",
    muscleGroups: ["back", "biceps"],
    category: "secondary",
    equipment: "cable",
    defaultCues: ["Lead with the elbows", "Squeeze the shoulder blades", "Don't rock the torso"],
  },
  {
    id: "single-arm-db-row",
    name: "Single-arm dumbbell row",
    muscleGroups: ["back", "biceps"],
    category: "secondary",
    equipment: "dumbbell",
    defaultCues: ["Flat back", "Row to the hip", "Full stretch at the bottom"],
  },
  {
    id: "inverted-row",
    name: "Inverted row",
    muscleGroups: ["back", "biceps"],
    category: "accessory",
    equipment: "bodyweight",
    defaultCues: ["Body in a straight line", "Pull chest to the bar", "Squeeze at the top"],
  },

  // ── Vertical pull — back/lats ───────────────────────────────────────────────
  {
    id: "pull-up",
    name: "Pull-up",
    muscleGroups: ["back", "biceps"],
    category: "primary",
    equipment: "bodyweight",
    isCoreLift: true,
    defaultCues: ["Start from a dead hang", "Drive elbows down", "Chest to the bar"],
  },
  {
    id: "lat-pulldown",
    name: "Close neutral grip lat pulldown",
    muscleGroups: ["back", "biceps"],
    category: "secondary",
    equipment: "machine",
    defaultCues: ["Bar to the collarbone", "Elbows down and in", "Control the way up"],
  },
  {
    id: "wide-lat-pulldown",
    name: "Wide grip lat pulldown",
    muscleGroups: ["back", "biceps"],
    category: "secondary",
    equipment: "machine",
    defaultCues: ["Slight lean back", "Lead with the elbows", "Full stretch overhead"],
  },
  {
    id: "assisted-pull-up",
    name: "Assisted pull-up",
    muscleGroups: ["back", "biceps"],
    category: "secondary",
    equipment: "machine",
    defaultCues: ["Full range each rep", "Drive elbows to the ribs", "Control the descent"],
  },

  // ── Arms — accessory/isolation ──────────────────────────────────────────────
  {
    id: "db-bicep-curl",
    name: "Dumbbell bicep curl",
    muscleGroups: ["biceps"],
    category: "accessory",
    equipment: "dumbbell",
    defaultCues: ["Elbows pinned to the sides", "No swinging", "Full squeeze at the top"],
  },
  {
    id: "barbell-curl",
    name: "Barbell curl",
    muscleGroups: ["biceps"],
    category: "accessory",
    equipment: "barbell",
    defaultCues: ["Keep elbows still", "Control the negative", "Don't lean back"],
  },
  {
    id: "hammer-curl",
    name: "Hammer curl",
    muscleGroups: ["biceps", "forearms"],
    category: "accessory",
    equipment: "dumbbell",
    defaultCues: ["Neutral grip", "Elbows fixed", "Slow eccentric"],
  },
  {
    id: "cable-curl",
    name: "Cable curl",
    muscleGroups: ["biceps"],
    category: "accessory",
    equipment: "cable",
    defaultCues: ["Constant tension", "Elbows at the sides", "Full range"],
  },
  {
    id: "tricep-pushdown",
    name: "Tricep pushdown",
    muscleGroups: ["triceps"],
    category: "accessory",
    equipment: "cable",
    defaultCues: ["Elbows pinned", "Full lockout", "Control back to the top"],
  },
  {
    id: "overhead-tricep-extension",
    name: "Overhead dumbbell tricep extension",
    muscleGroups: ["triceps"],
    category: "accessory",
    equipment: "dumbbell",
    defaultCues: ["Elbows point forward", "Full stretch behind the head", "Lock out overhead"],
  },
  {
    id: "lateral-raise",
    name: "Dumbbell lateral raise",
    muscleGroups: ["shoulders"],
    category: "accessory",
    equipment: "dumbbell",
    defaultCues: ["Lead with the elbows", "Slight forward lean", "No shrugging"],
  },

  // ── Legs — accessory/isolation ──────────────────────────────────────────────
  {
    id: "leg-curl",
    name: "Seated leg curl",
    muscleGroups: ["hamstrings"],
    category: "accessory",
    equipment: "machine",
    defaultCues: ["Full range", "Squeeze at the bottom", "Slow return"],
  },
  {
    id: "leg-extension",
    name: "Leg extension",
    muscleGroups: ["quads"],
    category: "accessory",
    equipment: "machine",
    defaultCues: ["Pause at the top", "Control the negative", "Toes neutral"],
  },
  {
    id: "calf-raise",
    name: "Standing calf raise",
    muscleGroups: ["calves"],
    category: "accessory",
    equipment: "machine",
    defaultCues: ["Full stretch at the bottom", "Pause at the top", "No bouncing"],
  },

  // ── Core (stable trackable core work) ───────────────────────────────────────
  {
    id: "pallof-press",
    name: "Anti-rotation core hold",
    muscleGroups: ["core"],
    category: "core",
    equipment: "cable",
    defaultCues: ["Resist the rotation", "Ribs down", "Breathe behind the brace"],
  },
  {
    id: "plank",
    name: "Plank",
    muscleGroups: ["core"],
    category: "core",
    equipment: "bodyweight",
    defaultCues: ["Straight line head to heels", "Squeeze glutes", "Don't let the hips sag"],
  },
  {
    id: "hanging-leg-raise",
    name: "Hanging leg raise",
    muscleGroups: ["core"],
    category: "core",
    equipment: "bodyweight",
    defaultCues: ["Control the swing", "Curl the pelvis up", "Lower slowly"],
  },

  // ── Correctives — rotated pool for anterior pelvic tilt (apt) ────────────────
  {
    id: "dead-bug",
    name: "Dead bug",
    muscleGroups: ["core"],
    category: "mobility",
    equipment: "bodyweight",
    correctiveGoal: "apt",
    defaultCues: ["Low back pressed to the floor", "Slow opposite arm/leg", "Exhale on the reach"],
  },
  {
    id: "glute-bridge",
    name: "Glute bridge",
    muscleGroups: ["glutes", "core"],
    category: "mobility",
    equipment: "bodyweight",
    correctiveGoal: "apt",
    defaultCues: ["Posterior tilt first", "Drive through the heels", "Squeeze at the top"],
  },
  {
    id: "hip-lift-90-90",
    name: "90/90 hip lift",
    muscleGroups: ["glutes", "core"],
    category: "mobility",
    equipment: "bodyweight",
    correctiveGoal: "apt",
    defaultCues: ["Reach the tailbone up", "Ribs down to the pelvis", "Feel the hamstrings"],
  },
  {
    id: "hip-flexor-stretch",
    name: "Half-kneeling hip flexor stretch",
    muscleGroups: ["hip-flexors"],
    category: "mobility",
    equipment: "bodyweight",
    correctiveGoal: "apt",
    defaultCues: ["Tuck the pelvis under", "Squeeze the back glute", "Tall through the torso"],
  },

  // ── Kettlebell — hinge & squat ──────────────────────────────────────────────
  // equipment: "kettlebell" is already admitted by equipmentForAccess for
  // full_gym / home_gym / limited_dumbbells, and correctly excluded for a
  // bodyweight-only user — no filter changes needed.
  {
    id: "kb-swing",
    name: "Kettlebell swing",
    muscleGroups: ["glutes", "hamstrings"],
    category: "secondary",
    equipment: "kettlebell",
    defaultCues: ["Hinge, don't squat", "Snap the hips, arms are ropes", "Float to chest height, no higher"],
  },
  {
    id: "kb-single-arm-swing",
    name: "Single-arm kettlebell swing",
    muscleGroups: ["glutes", "hamstrings", "back"],
    category: "secondary",
    equipment: "kettlebell",
    defaultCues: ["Shoulder packed down", "Resist the rotation", "Loose hand in the handle"],
  },
  {
    id: "kb-deadlift",
    name: "Kettlebell deadlift",
    muscleGroups: ["hamstrings", "glutes", "back"],
    category: "secondary",
    equipment: "kettlebell",
    defaultCues: ["Bell between the arches", "Push the floor away", "Lock out with the glutes"],
  },
  {
    id: "kb-single-leg-rdl",
    name: "Kettlebell single-leg RDL",
    muscleGroups: ["hamstrings", "glutes"],
    category: "secondary",
    equipment: "kettlebell",
    defaultCues: ["Hips square to the floor", "Back leg and torso move as one", "Soft standing knee"],
  },
  {
    id: "kb-goblet-squat",
    name: "Kettlebell goblet squat",
    muscleGroups: ["quads", "glutes"],
    category: "secondary",
    equipment: "kettlebell",
    defaultCues: ["Bell tight to the chest", "Elbows inside the knees", "Sit down, not back"],
  },
  {
    id: "kb-front-rack-squat",
    name: "Double kettlebell front rack squat",
    muscleGroups: ["quads", "glutes", "core"],
    category: "secondary",
    equipment: "kettlebell",
    defaultCues: ["Bells rest on the forearms", "Ribs down, chest tall", "Drive the knees out"],
  },
  {
    id: "kb-goblet-cossack-squat",
    name: "Goblet Cossack squat",
    muscleGroups: ["quads", "glutes", "hip-flexors"],
    category: "accessory",
    equipment: "kettlebell",
    defaultCues: ["Working heel stays down", "Straight leg's toes point up", "Chest up out of the hole"],
  },

  // ── Kettlebell — press, pull & carry ────────────────────────────────────────
  {
    id: "kb-clean",
    name: "Kettlebell clean",
    muscleGroups: ["glutes", "hamstrings", "shoulders", "back"],
    category: "secondary",
    equipment: "kettlebell",
    defaultCues: ["Zip the bell up the body", "Punch the hand through, don't flip", "Land soft in the rack"],
  },
  {
    id: "kb-push-press",
    name: "Kettlebell push press",
    muscleGroups: ["shoulders", "triceps"],
    category: "secondary",
    equipment: "kettlebell",
    defaultCues: ["Short dip, hard drive", "Ribs down at lockout", "Catch it in the rack coming down"],
  },
  {
    id: "kb-single-arm-press",
    name: "Single-arm kettlebell overhead press",
    muscleGroups: ["shoulders", "triceps"],
    category: "secondary",
    equipment: "kettlebell",
    defaultCues: ["Squeeze the opposite glute", "Bell path close to the head", "Bicep by the ear at lockout"],
  },
  {
    id: "kb-bent-over-row",
    name: "Kettlebell bent-over row",
    muscleGroups: ["back", "biceps"],
    category: "secondary",
    equipment: "kettlebell",
    defaultCues: ["Flat back, hips high", "Row to the hip, not the chest", "Full stretch each rep"],
  },
  {
    id: "kb-farmers-carry",
    name: "Kettlebell farmer's carry",
    muscleGroups: ["forearms", "back", "core"],
    category: "accessory",
    equipment: "kettlebell",
    defaultCues: ["Shoulders down and back", "Ribs stacked over hips", "Short, quiet steps"],
  },
  // The next two are category "core" on purpose: core work is never gated by the
  // active-lift list, so some kettlebell work reaches every user immediately.
  {
    id: "kb-suitcase-carry",
    name: "Kettlebell suitcase carry",
    muscleGroups: ["core", "forearms"],
    category: "core",
    equipment: "kettlebell",
    defaultCues: ["Don't let the loaded side dip", "Walk tall, no leaning", "Same distance each side"],
  },
  {
    id: "kb-turkish-get-up",
    name: "Turkish get-up",
    muscleGroups: ["core", "shoulders", "glutes"],
    category: "core",
    equipment: "kettlebell",
    defaultCues: ["Eyes on the bell the whole way", "One position at a time", "Reverse it exactly"],
  },

  // ── Core — anti-extension & anti-rotation ───────────────────────────────────
  // Ab wheel / sliders are tagged "bands" rather than "bodyweight" deliberately:
  // bodyweight is admitted unconditionally by every equipment filter, so a
  // bodyweight-only user would be prescribed kit they don't own. "bands" has the
  // right availability profile (home gym / dumbbells yes, bodyweight no).
  {
    id: "ab-wheel-rollout",
    name: "Ab wheel rollout",
    muscleGroups: ["core", "shoulders"],
    category: "core",
    equipment: "bands",
    defaultCues: ["Tuck the pelvis before you roll", "Ribs down the whole way", "Only as far as you hold the brace"],
  },
  {
    id: "band-pallof-press",
    name: "Band anti-rotation press",
    muscleGroups: ["core"],
    category: "core",
    equipment: "bands",
    defaultCues: ["Stand tall, resist the pull", "Press slow, return slower", "Breathe behind the brace"],
  },
  {
    id: "hollow-body-hold",
    name: "Hollow body hold",
    muscleGroups: ["core"],
    category: "core",
    equipment: "bodyweight",
    defaultCues: ["Low back glued to the floor", "Ribs down, arms by the ears", "Shorten the lever if the back lifts"],
  },
  {
    id: "side-plank",
    name: "Side plank",
    muscleGroups: ["core"],
    category: "core",
    equipment: "bodyweight",
    defaultCues: ["Stack the hips and shoulders", "Push the floor away", "Squeeze the top glute"],
  },
  {
    id: "bear-crawl-hold",
    name: "Bear crawl hold",
    muscleGroups: ["core", "shoulders"],
    category: "core",
    equipment: "bodyweight",
    defaultCues: ["Knees an inch off the floor", "Flat back, no rocking", "Breathe through the nose"],
  },
  {
    id: "copenhagen-plank",
    name: "Copenhagen plank",
    muscleGroups: ["core", "quads"],
    category: "core",
    equipment: "bodyweight",
    defaultCues: ["Top leg drives down into the bench", "Hips high and square", "Bend the bottom knee to regress"],
  },
  {
    id: "cable-woodchop",
    name: "Cable woodchop",
    muscleGroups: ["core", "shoulders"],
    category: "core",
    equipment: "cable",
    defaultCues: ["Rotate from the ribcage", "Arms stay long", "Pivot the back foot"],
  },

  // ── Core — flexion & loaded ─────────────────────────────────────────────────
  {
    id: "cable-crunch",
    name: "Cable crunch",
    muscleGroups: ["core"],
    category: "core",
    equipment: "cable",
    defaultCues: ["Round the spine, don't hip-hinge", "Hands stay by the head", "Exhale hard at the bottom"],
  },
  {
    id: "machine-ab-crunch",
    name: "Machine ab crunch",
    muscleGroups: ["core"],
    category: "core",
    equipment: "machine",
    defaultCues: ["Crunch the ribs to the hips", "Pause at the bottom", "Control all the way back"],
  },
  {
    id: "reverse-crunch",
    name: "Reverse crunch",
    muscleGroups: ["core"],
    category: "core",
    equipment: "bodyweight",
    defaultCues: ["Curl the pelvis, not the legs", "Lower back stays flat", "No momentum"],
  },
  {
    id: "hanging-knee-raise",
    name: "Hanging knee raise",
    muscleGroups: ["core", "hip-flexors"],
    category: "core",
    equipment: "bodyweight",
    defaultCues: ["Kill the swing first", "Posterior tilt at the top", "Lower under control"],
  },
  {
    id: "v-up",
    name: "V-up",
    muscleGroups: ["core"],
    category: "core",
    equipment: "bodyweight",
    defaultCues: ["Reach fingers to toes", "Move as one piece", "Lower slowly, don't crash"],
  },

  // ── Machines — lower body ───────────────────────────────────────────────────
  {
    id: "smith-machine-squat",
    name: "Smith machine squat",
    muscleGroups: ["quads", "glutes"],
    category: "secondary",
    equipment: "machine",
    defaultCues: ["Feet slightly forward", "Full depth under control", "Brace before unracking"],
  },
  {
    id: "belt-squat",
    name: "Belt squat",
    muscleGroups: ["quads", "glutes"],
    category: "secondary",
    equipment: "machine",
    defaultCues: ["Weight through mid-foot", "Tall chest, no spinal load", "Full range, no bounce"],
  },
  {
    id: "machine-hip-thrust",
    name: "Machine hip thrust",
    muscleGroups: ["glutes", "hamstrings"],
    category: "secondary",
    equipment: "machine",
    defaultCues: ["Chin tucked, ribs down", "Pause and squeeze at the top", "Shins vertical at lockout"],
  },
  {
    id: "lying-leg-curl",
    name: "Lying leg curl",
    muscleGroups: ["hamstrings"],
    category: "accessory",
    equipment: "machine",
    defaultCues: ["Hips stay down on the pad", "Squeeze at the top", "Slow the negative"],
  },
  {
    id: "seated-calf-raise",
    name: "Seated calf raise",
    muscleGroups: ["calves"],
    category: "accessory",
    equipment: "machine",
    defaultCues: ["Full stretch at the bottom", "Pause two counts at the top", "No bouncing"],
  },
  {
    id: "hip-abduction-machine",
    name: "Hip abduction machine",
    muscleGroups: ["glutes"],
    category: "accessory",
    equipment: "machine",
    defaultCues: ["Slight forward lean", "Push through the outside of the knee", "Control back to the start"],
  },
  {
    id: "hip-adduction-machine",
    name: "Hip adduction machine",
    muscleGroups: ["quads", "glutes"],
    category: "accessory",
    equipment: "machine",
    defaultCues: ["Sit tall, don't round", "Squeeze the pads together", "Open slowly"],
  },
  {
    id: "machine-glute-kickback",
    name: "Machine glute kickback",
    muscleGroups: ["glutes"],
    category: "accessory",
    equipment: "machine",
    defaultCues: ["Hips square to the pad", "No lower-back arch", "Squeeze at full extension"],
  },
  {
    id: "machine-back-extension",
    name: "Seated machine back extension",
    muscleGroups: ["lower-back", "glutes"],
    category: "accessory",
    equipment: "machine",
    defaultCues: ["Move from the hips", "Stop at neutral, don't hyperextend", "Slow both directions"],
  },

  // ── Machines — upper body ───────────────────────────────────────────────────
  {
    id: "machine-seated-row",
    name: "Seated machine row",
    muscleGroups: ["back", "biceps"],
    category: "secondary",
    equipment: "machine",
    defaultCues: ["Chest against the pad", "Elbows past the ribs", "Let the shoulder blades stretch forward"],
  },
  {
    id: "machine-row-unilateral",
    name: "Single-arm machine row",
    muscleGroups: ["back", "biceps"],
    category: "secondary",
    equipment: "machine",
    defaultCues: ["Reach forward at the start", "Drive the elbow to the hip", "Torso stays still"],
  },
  {
    id: "machine-incline-press",
    name: "Machine incline chest press",
    muscleGroups: ["chest", "shoulders", "triceps"],
    category: "secondary",
    equipment: "machine",
    defaultCues: ["Handles at upper chest", "Elbows at 45 degrees", "Full lockout, no slam"],
  },
  {
    id: "assisted-dip-machine",
    name: "Assisted dip machine",
    muscleGroups: ["chest", "triceps", "shoulders"],
    category: "secondary",
    equipment: "machine",
    defaultCues: ["Slight forward lean", "Elbows track back", "Stop at shoulder-parallel"],
  },
  {
    id: "pec-deck",
    name: "Pec deck fly",
    muscleGroups: ["chest"],
    category: "accessory",
    equipment: "machine",
    defaultCues: ["Soft elbows, fixed angle", "Squeeze for a beat", "Control the stretch"],
  },
  {
    id: "reverse-pec-deck",
    name: "Reverse pec deck",
    muscleGroups: ["back", "shoulders"],
    category: "accessory",
    equipment: "machine",
    defaultCues: ["Lead with the pinkies", "Chest stays on the pad", "No shrugging"],
  },
  {
    id: "machine-lateral-raise",
    name: "Machine lateral raise",
    muscleGroups: ["shoulders"],
    category: "accessory",
    equipment: "machine",
    defaultCues: ["Pivot at the shoulder", "Stop at shoulder height", "Slow the way down"],
  },
  {
    id: "machine-preacher-curl",
    name: "Machine preacher curl",
    muscleGroups: ["biceps"],
    category: "accessory",
    equipment: "machine",
    defaultCues: ["Armpits into the pad", "Full stretch at the bottom", "No shoulder swing"],
  },
  {
    id: "machine-tricep-extension",
    name: "Machine tricep extension",
    muscleGroups: ["triceps"],
    category: "accessory",
    equipment: "machine",
    defaultCues: ["Elbows pinned to the pad", "Full lockout", "Control the return"],
  },

  // ── Cable & band fills ──────────────────────────────────────────────────────
  {
    id: "cable-pull-through",
    name: "Cable pull-through",
    muscleGroups: ["glutes", "hamstrings"],
    category: "secondary",
    equipment: "cable",
    defaultCues: ["Hinge, don't squat", "Rope between the legs", "Finish with the glutes, not the low back"],
  },
  {
    id: "cable-face-pull",
    name: "Cable face pull",
    muscleGroups: ["back", "shoulders"],
    category: "accessory",
    equipment: "cable",
    defaultCues: ["Rope to the forehead", "Elbows high", "External rotation at the end"],
  },
  {
    id: "cable-chest-fly",
    name: "Cable chest fly",
    muscleGroups: ["chest"],
    category: "accessory",
    equipment: "cable",
    defaultCues: ["Fixed elbow angle", "Hug, don't press", "Cross slightly at the top"],
  },
  {
    id: "cable-lateral-raise",
    name: "Cable lateral raise",
    muscleGroups: ["shoulders"],
    category: "accessory",
    equipment: "cable",
    defaultCues: ["Cable behind the body", "Lead with the elbow", "Constant tension at the bottom"],
  },
  {
    id: "band-pull-apart",
    name: "Band pull-apart",
    muscleGroups: ["back", "shoulders"],
    category: "accessory",
    equipment: "bands",
    defaultCues: ["Arms long, chest tall", "Squeeze the shoulder blades", "Return under tension"],
  },

  // ── Barbell, dumbbell & bodyweight fills ────────────────────────────────────
  {
    id: "barbell-front-squat",
    name: "Barbell front squat",
    muscleGroups: ["quads", "glutes", "core"],
    category: "primary",
    equipment: "barbell",
    isCoreLift: true,
    defaultCues: ["Elbows up through the whole rep", "Brace hard before descending", "Stay upright out of the hole"],
  },
  {
    id: "barbell-conventional-deadlift",
    name: "Barbell conventional deadlift",
    muscleGroups: ["hamstrings", "glutes", "back", "lower-back"],
    category: "primary",
    equipment: "barbell",
    isCoreLift: true,
    defaultCues: ["Bar over mid-foot", "Lats tight, take the slack out", "Hips and chest rise together"],
  },
  {
    id: "barbell-bent-over-row",
    name: "Barbell bent-over row",
    muscleGroups: ["back", "biceps"],
    category: "primary",
    equipment: "barbell",
    isCoreLift: true,
    defaultCues: ["Torso around 45 degrees", "Row to the belly button", "No jerking with the hips"],
  },
  {
    id: "chin-up",
    name: "Chin-up",
    muscleGroups: ["back", "biceps"],
    category: "primary",
    equipment: "bodyweight",
    isCoreLift: true,
    defaultCues: ["Dead hang start", "Drive elbows to the ribs", "Chin clearly over the bar"],
  },
  {
    id: "incline-barbell-bench",
    name: "Incline barbell bench press",
    muscleGroups: ["chest", "shoulders", "triceps"],
    category: "secondary",
    equipment: "barbell",
    defaultCues: ["Bench at 30 degrees", "Bar to the upper chest", "Shoulder blades stay pinned"],
  },
  {
    id: "incline-db-bench-press",
    name: "Incline dumbbell bench press",
    muscleGroups: ["chest", "shoulders", "triceps"],
    category: "secondary",
    equipment: "dumbbell",
    defaultCues: ["Slight arch, ribs down", "Wrists over elbows", "Full stretch, no clanking"],
  },
  {
    id: "barbell-hip-thrust",
    name: "Barbell hip thrust",
    muscleGroups: ["glutes", "hamstrings"],
    category: "secondary",
    equipment: "barbell",
    defaultCues: ["Chin tucked, ribs down", "Shins vertical at the top", "Squeeze, don't arch"],
  },
  {
    id: "dip",
    name: "Dip",
    muscleGroups: ["chest", "triceps", "shoulders"],
    category: "secondary",
    equipment: "bodyweight",
    defaultCues: ["Shoulders stay above the elbows", "Slight forward lean", "Lock out without shrugging"],
  },
  {
    id: "db-shrug",
    name: "Dumbbell shrug",
    muscleGroups: ["back", "shoulders"],
    category: "accessory",
    equipment: "dumbbell",
    defaultCues: ["Straight up, not rolling", "Pause at the top", "Full stretch at the bottom"],
  },
  {
    id: "db-calf-raise",
    name: "Standing dumbbell calf raise",
    muscleGroups: ["calves"],
    category: "accessory",
    equipment: "dumbbell",
    defaultCues: ["Balls of the feet on a step", "Full stretch below", "Two-count squeeze at the top"],
  },
  {
    id: "push-up",
    name: "Push-up",
    muscleGroups: ["chest", "triceps", "shoulders"],
    category: "accessory",
    equipment: "bodyweight",
    defaultCues: ["Body in one straight line", "Elbows at 45 degrees", "Push the floor away at the top"],
  },
  {
    id: "nordic-curl",
    name: "Nordic hamstring curl",
    muscleGroups: ["hamstrings"],
    category: "accessory",
    equipment: "bodyweight",
    defaultCues: ["Hips locked, no piking", "Fight the whole way down", "Push off to reset"],
  },
  {
    id: "slider-hamstring-curl",
    name: "Slider hamstring curl",
    muscleGroups: ["hamstrings", "glutes"],
    category: "accessory",
    equipment: "bands",
    defaultCues: ["Hips stay high", "Slow the extension", "Squeeze the glutes throughout"],
  },

  // ── Correctives — added to the rotated apt pool ─────────────────────────────
  // Kept to correctiveGoal "apt" on purpose: the mobility slot doesn't filter on
  // correctiveGoal, so off-goal mobility work would just dilute this rotation.
  {
    id: "bird-dog",
    name: "Bird dog",
    muscleGroups: ["core", "lower-back"],
    category: "mobility",
    equipment: "bodyweight",
    correctiveGoal: "apt",
    defaultCues: ["Ribs down, no arching", "Reach long, don't lift high", "Pause at full extension"],
  },
  {
    id: "mcgill-curl-up",
    name: "McGill curl-up",
    muscleGroups: ["core"],
    category: "mobility",
    equipment: "bodyweight",
    correctiveGoal: "apt",
    defaultCues: ["Hands under the low back", "Head and shoulders lift as one", "Never flatten the spine"],
  },
  {
    id: "hip-90-90-rotation",
    name: "90/90 hip rotation",
    muscleGroups: ["hip-flexors", "glutes"],
    category: "mobility",
    equipment: "bodyweight",
    correctiveGoal: "apt",
    defaultCues: ["Chest tall throughout", "Move from the hips", "Pause at the end range"],
  },
  {
    id: "couch-stretch",
    name: "Couch stretch",
    muscleGroups: ["hip-flexors", "quads"],
    category: "mobility",
    equipment: "bodyweight",
    correctiveGoal: "apt",
    defaultCues: ["Tuck the pelvis first", "Squeeze the back glute", "Breathe out into the stretch"],
  },
];

// The single seeded standing exclusion at launch (PRD §6.1, §11.2).
export const SEED_EXCLUSION = {
  exerciseId: "chest-supported-row",
  exerciseName: "Chest-supported row machine",
  reason: "Ergonomic fit — doesn't suit my height/build",
};
